config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  get 'chat_messages/index'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:index, :show, :update, :edit, :destroy]
  resources :rooms, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
# frozen_string_literal: true

class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { maximum: 100 }

  after_create_commit { ChatMessageBroadcastJob.perform_later self }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_members
  has_many :users, through: :room_members
  has_many :chat_messages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/room_member.rb
class RoomMember < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true

  has_many :room_members, dependent: :destroy
  has_many :rooms, through: :room_members
  has_many :chat_messages, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :show]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.includes([:chat_messages, :users]).find(params[:id])
    @chat_message = ChatMessage.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      flash[:success] = 'ルームが作成されました'
      redirect_to @room
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user&.authenticate(params[:session][:password])
      log_in user
      # return redirect_to session[:callback] if session[:callback].present?
      redirect_to user
    else
      flash.now[:danger] = '無効なメールアドレス/ユーザー名の組み合わせです'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザー登録が完了しました'
      redirect_to @user
    else
      render 'new'
    end

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to @user, flash: { success: 'ユーザー情報が更新されました' }
    else
      render :edit
    end
    # respond_to do |format|
    #   if @user.update_attributes(user_params)
    #     format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to login_path, flash: { success: 'ユーザーが正常に削除されました' }
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'chat-app'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    # callback = session[:callback]
    reset_session
    session[:user_id] = user.id
    # session[:callback] = callback
    cookies.permanent.signed[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'ログインしてください'
      redirect_to login_url
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_messages/_chat_message.html.erb
<small class="text-muted">
  <%= "#{chat_message.user.name}" %>
  <%= chat_message.timestamp %>
</small>
<div>
  <%= "#{chat_message.content}" %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "chat-app", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'マイページ', user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/rooms/index.html.erb
<% provide(:title, 'チャットルーム一覧') %>
<H1>チャットルーム一覧</H1>

<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.name, room_path(room) %></li>
  <% end %>
</ul>

<%= link_to 'チャットルームの新規作成', new_room_path, class: 'btn btn-primary' %>

app/views/rooms/new.html.erb
<% provide(:title, 'チャットルームの新規作成') %>
<h1>ルームの作成</h1>

<%= form_for(@room) do |f| %>
  <%= render 'shared/error_messages', user: @room %>

  <div class="form-group">
    <%= f.label :name, 'ルーム名' %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "作成", class: 'btn btn-primary' %>
<% end %>

app/views/rooms/show.html.erb
<%= javascript_pack_tag 'rooms/show' %>
<% provide(:title, 'チャットルーム') %>

<H1><%= @room.name %></H1>

<div class="select">
  <label for="audioSource">音声入力: </label>
  <select id="audioSource"></select>
</div>
<div class="select">
  <label for="videoSource">映像入力: </label>
  <select id="videoSource"></select>
</div>

<div id="other-videos"></div>
<video id="self-video" muted autoplay playsinline></video>

<div id="step1">
  <p>カメラとマイクの使用を許可してください.</p>
  <div id="step1-error">
    <p>カメラとマイクにアクセスできません. ブラウザにカメラとマイクの使用を許可してください.</p>
    <a href="#" id="retry">Try again</a>
  </div>
</div>

<a href="#" id="end-call">End call</a>

<ul>
  <% @room.users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

<div id='chat_messages' data-room-id="<%= @room.id %>">
  <%= render @room.chat_messages %>
</div>

<%= form_for @chat_message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control' %>
    <small class="text-muted">最大100文字です</small>
  </div>

  <%= f.submit "発言する", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul id="error-messages">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, url: signup_path) do |f| %>
  <%= render 'shared/error_messages', user: user %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit "ユーザーの新規登録", class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, 'ユーザー情報の編集') %>
<h1>Edit User</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', user: @user %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group" %>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group" %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group" %>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit "Save chonges", class: 'btn btn-primary' %>
    <% end %>

    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<H1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <% if logged_in? %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "退会しますか?" } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'ユーザーの新規登録', signup_path %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザーの新規登録') %>
<h1>ユーザーの新規登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path, class: 'btn btn-primary' %>

app/views/users/show.html.erb
<% provide(:title, 'ユーザー情報') %>
<h1>ユーザー情報</h1>
<div>
  <strong>Name: </strong>
  <span id="name"><%= @user.name %></span>
</div>
<div>
  <strong>Email: </strong>
  <span id="email"><%= @user.email %></span>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'User list', users_path %>